name: "Build and push"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  TEAM_NAME: "<change this>"
  REGISTRY: "<change to your acr url>"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git checkout"
        uses: "actions/checkout@v2"

      - name: "Set docker image string env var"
        run: |
          echo "DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.TEAM_NAME }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: "Build Container Image"
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: "Login to Azure Container Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: "Push Container Image"
        run: |
          docker push ${{ env.DOCKER_IMAGE }}